### PR TITLE
Single-value binding of antibody with reporter to antigen assay #1203

### PR DESCRIPTION
**Pull request by turbomam**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
You should run `git diff` before committing (or pushing) your changes -- that's step 5 in this part of the README:

https://github.com/obi-ontology/obi#making-changes

The `git diff` will show that every line of the `assays.tsv` template has changed. That's bad. `make sort` should fix it. Without a good diff, it's very difficult to review a PR.

**Comment by turbomam** [comment]
Sorry about the garbled assays template, @jamesaoverton . Thanks for the feedback. I just ran `make sort`, but at least in my local environment there's still pages of different lines. I committed locally and can push now if that's best.

There was a message on this page about my branch being out of sync with master, so I impulsively clicked a button with a label like "refresh".

**Comment by jamesaoverton** [comment]
`git diff` compares your unstaged changes to the HEAD (last commit). In this case the last commit has bad line endings, so running `make sort` and `git diff` will show that all the lines have changed (i.e. been fixed).

What we really want is to compare the results of `make sort` to the `master` branch. So the right command is `git diff master -- src/ontology/templates/assays.tsv`.

When I pulled this branch and ran `make sort` and `git diff master -- src/ontology/templates/assays.tsv` the results looked good. So I pushed them. You should now see a clean diff on the "Files changed" tab. Please confirm that it has the changes you want.

**Comment by turbomam** [comment]
Looks good. Thanks. Do I need to wait for anything before I add my LOINC-inspired assays into the OBI assay template?

**Pull request merged**
