### PR TITLE
Fix xml:base and external-byhand.owl IRI

### PR DESCRIPTION
**Pull request by jamesaoverton**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This should fix #940.

@DanBerrios: Can you please test this?

**Comment by DanBerrios** [comment]
@jamesaoverton I pulled in the branch... but I still see the same error messages.  I can screen share with you and show you...

**Comment by jamesaoverton** [comment]
@DanBerrios I made one more tweak to this `fix-940` branch. Can you please pull it and try again?

**Comment by rctauber** [comment]
This does not fully resolve #940 but we are merging this fix in.

**Pull request merged**
