### PR TITLE
Assay terms from VEuPath

### PR DESCRIPTION
**Pull request by johnwjudkins**
#1322

### CODE REVIEW

**Comment by johnwjudkins** [comment]
This pull request includes external ontology terms to use in axioms for 'parasite detection assay' and 'Plasmodium gametocyte detection assay' - this is causing the check to fail.

**Comment by jamesaoverton** [comment]
I will update the imports to try and make this pass the tests.

**Comment by jamesaoverton** [comment]
I updated various imports and modules, but then I got stuck. Some new rows in `assays.tsv` refer to 'clinical laboratory test', which is not in OBI or this PR. I believe this refers to <http://purl.obolibrary.org/obo/OGMS_0000056> mentioned here in #1379. What would you like to do?

**Comment by zhengj2007** [comment]
Discussed on OBI call 2021-08-09. Proposed to change the parent of 'blood test', 'urine test' to 'assay' and make them as defined class, such as input is 'blood specimen' or evaluate is 'blood'.

**Comment by jamesaoverton** [comment]
@johnwjudkins: I believe that @zhengj2007 was suggesting that 'blood test' and 'urine test' be defined using equivalent class axioms. I tried it locally and it seemed to work well. Would you be OK if I make this change?

**Comment by johnwjudkins** [comment]
@jamesaoverton Yes, those changes are fine, thanks.

**Comment by jamesaoverton** [comment]
Thanks!

**Pull request merged**
