### PR TITLE
genome coverage defn simplification #1634

### PR DESCRIPTION
**Pull request by ddooley**
Line 18376 of foodon-edit.owl diff is where change is.  Unfortunately there's some non-determinism still moving annotations around everywhere.  What to do?

### CODE REVIEW

**Comment by jamesaoverton** [comment]
What's the exact version of Protege that you used for this?

**Comment by ddooley** [comment]
image

I don't have to update the Protege OWLAPI separately from installing protege do I?

**Comment by jamesaoverton** [comment]
No, OWLAPI is a fundamental part of Protege, not a plugin.

Do you have other plugins installed?

**Comment by jamesaoverton** [comment]
Damien Goutte-Gattat debugged this in the OBO Slack. I should have run `robot convert` twice for each file in #1676. This should not be a problem going forward.

You can proceed with this PR if you like, or wait for me to update all the files again, which I may not get to for a few days.

**Comment by ddooley** [comment]
Aha!  Ok, go ahead at your leisure.  This pull isn't in a hurry.

**Pull request closed without merging**
