### PR TITLE
ordinal value specification and singleX ATAC

### LINKED ISSUE #862: ordinal value specification
Due to the interest in ordinal value specifications, I'd like to take a small but concrete step as soon as possible.  Let's discuss this on Monday September 11th.

create "ordinal value specification" as a subclass of "categorical value specification", <http://purl.obolibrary.org/obo/OBI_0001930> with URI <http://purl.obolibrary.org/obo/OBI_0002930>

proposed definition:  "a categorical value specification in which the available categories have a natural order and the distances between the categories is not known" from https://en.wikipedia.org/wiki/Ordinal_data

example of use:  "A RNA integrity number of 1 indicates RNA that is more highly degraded than RIN 9"

Future steps:  
 - what kind of class would contain multiple ordinal (or categorical) value specifications like 'infant', 'neonate' and 'toddler'?  I.e., how to express which ordinal values are legal in a given context?
 - what classes or properties to create, in order to express the rank of a ordinal value specification ('infant' = 2, 'neonate' =1, 'toddler'=3)?

### PR DESCRIPTION
**Pull request by turbomam**
Fixes #862 and #864

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Travis is failing because the new assays should be entered into the `assay.tsv` and not `obi-edit.owl`.

**Comment by turbomam** [comment]
I think [ordinal value specification](http://purl.obolibrary.org/obo/OBI_0003001) for #862 got in here, too.

**Comment by jamesaoverton** [comment]
The diff for the `assays.tsv` file is a mess. Can you please run the [sort-templates.py](https://github.com/obi-ontology/obi/blob/master/src/scripts/sort-templates.py) script to clean it up?

**Comment by jamesaoverton** [comment]
I fixed merge conflicts and assigned IDs using the [OBI Term ID Reservation](https://docs.google.com/spreadsheets/d/1tpDrSiO1DlEqkvZjrDSJrMm7OvH9GletljaR-SDeMTI/edit#gid=224833299) sheet:

OBI:0002756 ordinal value specification
OBI:0002757 single-nucleus ATAC-seq
OBI:0002758 single-cell ATAC-seq

**Pull request merged**
