### PR TITLE
Release Candidate 2022-06-14

### PR DESCRIPTION
**Pull request by jamesaoverton**
New terms added:

ID | Label
---|---
OBI:0002830|catheter
OBI:0003297|tyramide signal amplification sequencing assay
OBI:0003298|DNA adenine methyltransferase identification assay
OBI:0003299|DamID-seq
OBI:0003300|nucleolus-associated domain sequencing assay
OBI:0003301|DNase Hi-C assay
OBI:0003302|micro-C assay
OBI:0003303|single cell combinatorial indexing Hi-C assay
OBI:0003304|single nucleus Hi-C assay
OBI:0003305|single cell Hi-C assay
OBI:0003306|bulk Hi-C assay
OBI:0003307|multi-contact Hi-C assay
OBI:0003309|transposase-mediated analysis of chromatin looping assay
OBI:0003310|split-pool recognition of interactions and tag extension assay
OBI:0003311|DNA split-pool recognition of interactions and tag extension assay
OBI:0003312|RNA-DNA split-pool recognition of interactions and tag extension assay
OBI:0003313|genome architecture mapping assay
OBI:0003314|mapping RNA-genome interactions assay
OBI:0003315|assay measuring epitope specific amphiregulin production by T cells
OBI:0003316|ELISA measuring epitope specific amphiregulin production by T cells
OBI:0003317|perforin release during T cell degranulation
OBI:0003318|granzyme A release during T cell degranulation
OBI:0003319|granzyme B release during T cell degranulation
OBI:0003320|granulysin release during T cell degranulation
OBI:0003321|venous blood microbiology assay
OBI:0003323|high throughput multiplexed assay measuring binding of a B cell epitope:antibody complex
OBI:0003324|high throughput multiplexed assay measuring binding of a T cell epitope:MHC:TCR complex
OBI:0003325|high throughput multiplexed assay measuring binding of a MHC:ligand complex
OBI:0003326|high throughput multiplexed assay measuring MHC ligand processing and presentation
OBI:0003365|milk assay datum
OBI:0003366|organism diagnostic process
OBI:0003367|diagnosis of an organism
OBI:0003368|detection technique
OBI:0003369|assay kit
OBI:0003371|epitope specific XCL1 release by T cells
OBI:0003372|assay measuring epitope specific lymphotactin production by T cells
OBI:0003373|ELISA measuring epitope specific lymphotactin production by T cells
OBI:0003374|remote patient assessment
OBI:0003380|placental blood specimen
OBI:0003381|placental blood microbiology assay
OBI:0003382|placental blood microbiology datum
OBI:0003383|eukaryota in placental blood datum
OBI:0003385|has assay target context

### CODE REVIEW

**Comment by johnwjudkins** [comment]
Can we fix the definitions for these terms? They have "A induced sputum..." instead of "An induced sputum...". Thanks.

OBI:0003268
OBI:0003269
OBI:0003270

Everything else looks good.

**Comment by cmungall** [comment]
I noticed that you are introducing your own biological process classes and placing them as subclasses of existing GO classes, e.g. "granzyme A release during T cell degranulation", in order to define assays

We discussed this internally (@pgaudet @thomaspd), we would propose that the assay is defined separately in terms of a measurement (granzyme A)  to support an inference T cell degranulation has occurred. So some triple like [OBI assay] “used to demonstrate the occurrence of” [GO BP] would give us a link to GO that is more inline with current curation practice, as it’s really about the role of an experiment as evidence for a biological inference.

**Comment by jamesaoverton** [comment]
@johnwjudkins' fixes are easy, but I'll hold off on this RC until OBI developers can discuss @cmungall's concern. I'll add it to Monday's agenda, but I won't be on that call.

**Comment by cmungall** [comment]
I don't want to hold up a release - if you wish to proceed you always have the option of making changes later, I just wanted to make sure this was noted

**Comment by rvita** [comment]
We had a call with GO people not that long ago where we discussed this and explained why we do it this way and the explanation was accepted. It can be true that the protein being produced is not directly measured and we do not want two separate assays for when it is and when it is not. Also sometimes it is a release of pre-existing proteins.

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2022-07-11:

@cmungall Our understanding is that we got buy-in from GO on this modelling, as [discussed here](https://github.com/obi-ontology/obi/issues/1482#issuecomment-1038451972) for example. We will release this modelling now, and if it needs to be fixed later please open an issue.

My plan is:

1. close this PR without merging
2. make the three small fixes @johnwjudkins requested
3. make a release -- no more review required

**Pull request closed without merging**
