### PR TITLE
[WIP] Start adding new view for NIAID-GSC-BRC

### LINKED ISSUE #1127: Generation of NIAID-GSC-BRC view during OBI release
The U.S. National Institute of Allergy and Infectious Diseases (NIAID), the Genomic Sequencing Centers (GSCIDs) and Bioinformatics Resource Centers (BRCs) developed the [GSCID/BRC Project and Sample Application Standard](https://www.niaid.nih.gov/research/human-pathogen-and-vector-sequencing-metadata-standards) for capturing standardized genome sequence metadata.

Each field in the Core Project, Core Sample, and Sequencing Assay standards are mapped to an ontology term in OBO Foundry ontologies. These ontology terms are available in OBI with 'NIAID GSCID-BRC alternative term' annotation indicated the field name in the standards. Details of how the standards developed and associated with OBI are described in the paper, [Standardized metadata for human pathogen/vector genomic sequences](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4061050/).

We propose to generate a NIAID-GSC-BRC view during OBI release. The view will contain all the standard field mapped ontology terms and associated terms. The ontology terms used in the standards are listed on google sheet, https://drive.google.com/file/d/1tZEOHoR6PQ2VHsalij0yOf0iMBmArwdj/view?usp=sharing

### PR DESCRIPTION
**Pull request by jamesaoverton**
Add a new view for NIAID-GSC-BRC, which will replace the previous version from ~5 years ago.

Resolves #1127

### CODE REVIEW

**Comment by jamesaoverton** [comment]
@zhengj2007 This is a first pass. I need you to look at the OWL file and answer some questions:

1. This uses `robot extract --method STAR`, which takes the terms you specified and then recursively finds all their logical dependencies until it forms a logically complete "module". In a richly axiomatized ontology such as OBI, STAR usually brings in a lot of terms. Is this what you want, or do you want to use a different extraction method, such as MIREOT?

For `obi_core.owl` we remove certain classes before running STAR, because they bring in too many other things: https://github.com/obi-ontology/obi/blob/master/Makefile#L155 If you want to do that, let me know.

2. Do you want to use your "BRC Label"s as the `rdfs:label`s for the terms you specified?

3. Do you want to include the "Field ID" as an annotation? If so, what annotation property should it use?

4. What general annotation properties do you want to use? The current version does not include any, because there aren't any on your sheet. For `obi_core.owl` we specify a set of them: https://github.com/obi-ontology/obi/blob/master/src/ontology/views/core.txt#L51 Or we could import OMO into your view.

**Comment by zhengj2007** [comment]
@jamesaoverton Thanks a lot for working on it. Please see my comments inline.

> @zhengj2007 This is a first pass. I need you to look at the OWL file and answer some questions:
> 
> 1. This uses `robot extract --method STAR`, which takes the terms you specified and then recursively finds all their logical dependencies until it forms a logically complete "module". In a richly axiomatized ontology such as OBI, STAR usually brings in a lot of terms. Is this what you want, or do you want to use a different extraction method, such as MIREOT?

Yes. It is what we want. The view looks good to me.

> For `obi_core.owl` we remove certain classes before running STAR, because they bring in too many other things: https://github.com/obi-ontology/obi/blob/master/Makefile#L155 If you want to do that, let me know.
> 
> 1. Do you want to use your "BRC Label"s as the `rdfs:label`s for the terms you specified?

No. We'd like to use OBI labels.

> 2. Do you want to include the "Field ID" as an annotation? If so, what annotation property should it use?

Yes. I just realized we made an annotation property (http://purl.obolibrary.org/obo/OBI_GSCID_BRC_Field_ID) when used ontoDog to generate the view. Do you mind to add the annotation property for field_ID in OBI?  

> 3. What general annotation properties do you want to use? The current version does not include any, because there aren't any on your sheet. For `obi_core.owl` we specify a set of them: https://github.com/obi-ontology/obi/blob/master/src/ontology/views/core.txt#L51 Or we could import OMO into your view.

We'd like to include the annotation properties as what obi-core.owl did. Here is the list:
http://purl.obolibrary.org/obo/BFO_0000179 #BFO OWL specification label
http://purl.obolibrary.org/obo/BFO_0000180 #BFO CLIF specification label
http://purl.obolibrary.org/obo/IAO_0000111 #editor preferred label
http://purl.obolibrary.org/obo/IAO_0000112 #example of usage
http://purl.obolibrary.org/obo/IAO_0000114 #has curation status
http://purl.obolibrary.org/obo/IAO_0000115 #definition
http://purl.obolibrary.org/obo/IAO_0000116 #editor note
http://purl.obolibrary.org/obo/IAO_0000117 #term editor
http://purl.obolibrary.org/obo/IAO_0000118 #alternative term
http://purl.obolibrary.org/obo/IAO_0000119 #definition source
http://purl.obolibrary.org/obo/IAO_0000232 #curator note
http://purl.obolibrary.org/obo/IAO_0000233 #term tracker item
http://purl.obolibrary.org/obo/IAO_0000234 #ontology term requester
http://purl.obolibrary.org/obo/IAO_0000412 #imported from
http://purl.obolibrary.org/obo/IAO_0000589 #OBO foundry unique label
http://purl.obolibrary.org/obo/IAO_0000600 #elucidation
http://purl.obolibrary.org/obo/IAO_0000601 #has associated axiom(nl)
http://purl.obolibrary.org/obo/IAO_0000602 #has associated axiom(fol)
http://purl.obolibrary.org/obo/OBI_0001886 #NIAID GSCID-BRC alternative term
http://purl.obolibrary.org/obo/RO_0001900 #temporal interpretation

If possible, I'd like to exclude following annotation properties associated with the terms. 
http://purl.obolibrary.org/obo/IAO_0010000 #has axiom label
http://purl.obolibrary.org/obo/OBI_0001847 #ISA alternative term
http://purl.obolibrary.org/obo/OBI_9991118 #IEDB alternative term

If it is not easy to do, it is fine to include them in the NIAID GSCID-BRC view.

**Comment by jamesaoverton** [comment]
@zhengj2007 I made those changes. Please take another look.

**Comment by zhengj2007** [comment]
@jamesaoverton Thanks a lot for making updates.

It's my fault to include the "OBO foundry unique label" annotation property that is not used in anywhere. Could you please remove it?
http://purl.obolibrary.org/obo/IAO_0000589 #OBO foundry unique label

The IRI for the view ontology may need to be updated. Current they are:
ontology IRI: http://purl.obolibrary.org/obo/obi/.owl (same as obi.owl)
ontology version IRI: http://purl.obolibrary.org/obo/obi/2020-04-08/.owl

We used following ontology IRI before:
http://purl.obolibrary.org/obo/obi/NIAID-GSC-BRC.owl

Besides, the view used the ontology description same as the OBI one. It would be nice to have its own description. But it is fine to keep as it is if it is not easy to update.

Here is the description of OBI NIAID-GSC-BRC view:
"A subset of OBI containing all terms specified by the NIAID GSCID and BRC Project, Sample and Sequencing Assay Core Metadata Standards. This OBI view includes NIAID GSCID and BRC community preferred labels and field IDs specified in the standards (https://www.niaid.nih.gov/research/human-pathogen-and-vector-sequencing-metadata-standards)."

[Notes: If we can use different ontology description for the view, we may think to update the description of obi-core view as well.]

**Comment by jamesaoverton** [comment]
Thanks for catching the problem with the ontology IRI and version IRI. I've made the rest of the requested changes.

**Pull request merged**
