### PR TITLE
Adding new COA terms under Assay>physical examination of individual

### PR DESCRIPTION
**Pull request by Daniel-Olson**
Fixes issue #1637 

Supersedes #1641 

@jamesaoverton 

I have updated the definitions per @bpeters42 request and changed the hierarchy to accommodate physical examination of individual.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
@Daniel-Olson Can you please replace 'limits of stability test' with its new label 'limits of stability assessment' throughout. That's what's causing the automated tests to fail.

**Comment by Daniel-Olson** [comment]
I added the new OBA IDs to the new template (physical-examination.tsv).

**Comment by ehartley** [comment]
@jamesaoverton We used the OBA IDs instead of the labels in the "assessed biological trait" column because the terms are in the process of being added to OBA as part of [this PR](https://github.com/obophenotype/bio-attribute-ontology/pull/201). So should wait to merge this PR until these new OBA IDs have been released, which will happen soon (Nico is working on it).

**Comment by jamesaoverton** [comment]
Sorry for the series of delays. I made a few changes that you should know about:

1. use the OBA labels in the template, instead of the term IDs
2. change the 'anatomical site' axiom from "'is about' some %" to "has_specified_output some ('is about' some %)"; the domain of 'is about' is 'information content entities', but 'assay' is a 'process', so the old axiom just doesn't work
3. remove some unused columns

**Pull request merged**
