### PR TITLE
scalar measurement datum adjustment, issue 1263

### PR DESCRIPTION
**Pull request by ddooley**
Removing 'has measurement unit label' min 1 Thing
Removing 'has measurement value' min 1 rdfs:Literal
per issue https://github.com/obi-ontology/obi/issues/1263
These axioms are archaic, they were outdated with introduction of axiom: 'has value specification' some 'scalar value specification'

### CODE REVIEW

**Comment by ddooley** [comment]
Additionally,  a 'scalar measurement datum' has a 'scalar value specification' with a  'has measurement unit label' axiom.  We are moving to relax this, barring any objections. Not all scalars have units.

**Comment by jamesaoverton** [comment]
Can you please make these changes in `src/ontology/` (probably `obi-edit.owl`)?

The `obi.owl` file is automatically generated, so these changes will be lost on rebuild. Also they won't be reflected in any of the other generated files, such as OBI Core.

**Comment by ddooley** [comment]
Argh, thank's for catching that. I edited a copy I had open without even thinking of checking.  Will do.

**Comment by ddooley** [comment]
Revised in separate pull requests to obi-edit.owl and iao-edit.owl (#241)

**Comment by alanruttenberg** [comment]
It is uncool to change the meaning of an existing term. Please define a new term instead.

**Comment by ddooley** [comment]
Hi Alan. So I'm almost always for that, and some suggestions are happening in that regard.  This particular "scalar measurement datum" issue is dealing with a logical/data structure conundrum - that "scalar measurement datum" currently has a value specification AND direct measurement value/unit in its axioms.  I think the problem was introduced the moment value specification was added to it years ago, and never cleared up.  Do we leave these conflating axioms as is, and deprecate "scalar measurement datum" since it is practically unusable with them in place?  

Personally I am ok with deprecating "scalar measurement datum" and creating cleaner replacements: a unitless "scalar measurement data item" and "unit-bearing scalar measurement data item". 

But there remains the issue of preferring "value specification" over direct attachment of measurement value/unit to a data item. Where do you stand on that?  

The upcoming COB of course seems to be offering an alternative with its "has quantity" which is a third and apparently simpler construct from the eyes of graph db folks as it incorporates both value and optionally user defined unit.

**Comment by alanruttenberg** [comment]
Hi, 

Thanks for a clear description of the issue. I concur that the problem originates with the addition of value specification. It's at that point that it would have been better to deprecate. I'm wondering if a property chain could be used to populate the unit from the value specification.

However, it should be noted that the SI specifies that dimensionless quantities have a unit: 1. Moreover this [NIST paper](https://iopscience.iop.org/article/10.1088/0026-1394/52/1/40) suggests that such dimensionless aren't always coherent, and suggests additional "units" to replace 1 are needed.  Even considering ratios, if the quantities have no dimension, that suggests that dimensionless quantities can be combined, for instance added, and that's not the case.

In my view, It's unfortunate that the replacement value specification includes no constraints at all. 

I don't understand what the COB is saying about has quantity. FWIW I'm a 'graph db' folk - probably used it before any others in OBO. Still, I don't make ontological decisions based on an implementation of a store. The recommendation to use a user-defined datatype will mean that the OWL reasoners will error out or ignore them.  

I'm not sure what to do here. It's a mess.

**Pull request closed without merging**
