### PR TITLE
Add pooled clone seq assay Issue 1106

### PR DESCRIPTION
**Pull request by DanBerrios**

### CODE REVIEW

**Comment by bpeters42** [comment]
The definition should refer to the parent class: 

A DNA sequencing assay in which the DNA input is derived from pooled clones such as BACs and Fosmids. 


--

**Comment by bpeters42** [comment]
The 'make sort' should ideally be run prior to commit.

**Review by bpeters42 — CHANGES_REQUESTED** [review]
See comments.

**Review by bpeters42 — APPROVED** [review]

**Comment by DanBerrios** [comment]
FYI, I gave up on editing the tsv on Windows Excel..there was no way to export the file that didn't cause quoting (that I could find). I edited in NotePad++.  Does anyone know if OpenOffice Calc causes problems too?

**Comment by jamesaoverton** [comment]
The `make sort` script is supposed to fix the quoting but I think it isn't. @beckyjackson make a new version here that fixes that: https://github.com/obi-ontology/obi/blob/standardize-templates/src/scripts/sort-templates.py

There's another problem for display on GitHub that I'm trying to fix.

**Comment by beckyjackson** [comment]
Missing newline in `devices.tsv` showed up when I ran `make sort`, which is why that file still has a change.

**Pull request merged**
