### PR TITLE
duplicate specified i/o definition fix

### PR DESCRIPTION
**Pull request by ddooley**
Issue #1123 has_specified_input and has_specified_output duplicate definition of inverse relation.  Tweaking this.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I think these two terms are also coming from the IAO import, so we get both the old and the new proposed definitions, which fails our test for multiple textual definitions. The solution would be to (1) edit the IAO import, as a temporary fix, and (2) update IAO, as a permanent fix.

**Comment by jamesaoverton** [comment]
Discussed on the 2021-08-16 call: No objections. This is a little tricky. I'll work on it when I get a chance.

**Comment by jamesaoverton** [comment]
I'm tempted to just use a SPARQL query to remove the old definitions somewhere late in our build process. @beckyjackson can you please give that a try?

**Comment by beckyjackson** [comment]
@jamesaoverton I added a SPARQL update to remove the bad definitions from the merged version of OBI. This fix will only appear in the OBI release, not in the edit file.

**Pull request merged**
