### PR TITLE
New assay terms & updates from IGS

### LINKED ISSUE #1192: NTR: CUT&RUN assay
Hello, we would like to request a term for some new experiment submissions we would to annotate.

**editor preferred term:** Cleavage Under Targets and Release Using Nuclease
**alternate terms:** CUT&RUN
**textual definition:** An in situ chromatin profiling assay in which antibody-targeted controlled cleavage by micrococcal nuclease releases specific protein-DNA complexes into the the supernatant for sequencing. 
**definition source for the textual definition:** https://elifesciences.org/articles/21856
**logical definition:** DNA sequencing assay (OBI:0000626) —> CUT&RUN 

Thank you for your help!

### LINKED ISSUE #1243: Draft NTRs for LINCS assays
Hi,

LINCS is a data center that is part of the CFDE and they are using a bunch of assays not yet in OBI.
Here is a link to a set of draft NTRs to capture these assays:
https://docs.google.com/spreadsheets/d/1N5L_uwwVj7w0h6Gh3fMdaTbGV01OnUP-Ts2sgBAxVKs/edit?usp=sharing

Some specific questions related to these terms:
1. A couple of the terms needed are actually brand-name assays that companies offer. 
Is it ok to have an OBI term like that? I looked around the assay branch for examples, but couldn't find any.
Here are two examples of what I mean - they are both assays for kinase inhibitors and are a product/service from a company:
-KINOMEscan -  https://www.discoverx.com/services/drug-discovery-development-services/kinase-profiling/kinomescan
-KiNativ  - http://www.kinativ.com/
Here is what I have proposed for these terms:
--assay (OBI:0000070)
----kinase inhibitor assay (OBI:new)
------KINOMEscan assay (OBI:new)
------KiNativ assay (OBI:new)

2. What does it take in order for an assay to be established with a name. Is it enough to call something a named assay if people have published on it? For example: people from the Broad Institute have established a proteomic profiling method for 100 phosphoproteins - they call it "P100".  Publication is PMID:26912667
Would it be ok to have an OBI term that was "P100 phosphoprotein quantification assay" ?

3. When does OBI make grouping terms - only when you have more than one of a particular category? Or do you make them thinking it likely that you'll have more terms in that category later?
For example: I need the following term for LINCS: "fluorescence imaging-based apoptosis assay".
Should I make a parent term "apoptosis assay" along with the above term? Or just make the above term?
In the current draft, I've made the grouping parents in these cases, but I wasn't sure if that was the right thing to do.

Thanks,
Michelle

### LINKED ISSUE #1365: western blot assay questions
Hello,
Some questions related to existing Western blot terms:

1. Why is the term label for OBI:0000854 'western blot analysis' instead of 'western blot assay' when it is a term in the assay branch?
2. Shouldn't there be a linkage between OBI:0001669 'far-Western blot assay' and 'western blot analysis' ('western blot assay'). It seems that far-Western should be a child of western (inferred child?). Currently OBI:0001669 is a child of 'binding assay' OBI:0001146. And related to this, should OBI:0000854 'western blot analysis (assay)' be linked to 'binding assay' OBI:0001146?
3. Small note: "western" should not be capitalized in OBI:0001669.

Thanks,
Michelle

### PR DESCRIPTION
**Pull request by beckyjackson**
This PR includes 25 new assays for CFDE (resolves #1243), two assays for CUT&RUN (resolves #1192), and two changes (resolves #1365):
* Rename 'western blot analysis' to 'western blot assay'
* Rename 'far-Western blot assay' to 'far-western blot assay' & add 'western blot assay' as the detection technique

Here is a summary of the new terms:
ID | Label
-- | --
OBI:0002946 | fluorescence   imaging-based apoptosis assay
OBI:0002947 | fluorescence   imaging-based cell proliferation assay
OBI:0002948 | fluroescence   imaging-based cell cycle state assay
OBI:0002949 | fluorescence   imaging-based cell viability assay
OBI:0002950 | fluorescence   imaging-based drug synergy assay
OBI:0002951 | fluorescence   imaging-based cell morphology assay
OBI:0002952 | fluorescence   imaging multiplex cytological profiling
OBI:0002953 | protein   state assay
OBI:0002954 | fluorescence   imaging-based protein phosphorylation state assay
OBI:0002955 | mass   spectrometry-based protein state assay
OBI:0002956 | targeted,   drug-modulated, mass spectrometry-based protein phoshporylation-state assay
OBI:0002957 | reverse   phase protein array profiling assay
OBI:0002958 | SWATH-MS   protein profiling assay
OBI:0002959 | tandem   mass tag mass spectrometry
OBI:0002960 | fluorescence   imaging-based reporter gene assay
OBI:0002961 | global   chromatin profiling by mass spectrometry assay
OBI:0002962 | kinase   inhibitor assay
OBI:0002963 | KINOMEscan   assay
OBI:0002964 | KiNativ   assay
OBI:0002965 | landmark   transcript profiling assay
OBI:0002966 | microenvironment   microarray assay
OBI:0002967 | microwestern   meso-scale quantitative western blot assay
OBI:0002968 | positive/negative   ion switching metabolite profiling assay
OBI:0002969 | cyclic   immunoflouroescence assay
OBI:0002970 | multiplex   bead-based protein state immunoassay
OBI:0003033 | cleavage   under targets and release using nuclease assay
OBI:0003034 | cleavage   under targets and tagmentation

cc @mgiglio99 @nsuvarnaiari

### CODE REVIEW

**Comment by jamesaoverton** [comment]
As discussed on 2021-07-26, I will wait a bit longer to review this. @mgiglio99 please let me know when I should move ahead.

**Comment by mgiglio99** [comment]
Hi @jamesaoverton we have checked these and it's safe to move ahead with them as submitted in the pull request.

Do we need to worry about the branch conflicts that we see mentioned above?

Thanks,
Michelle

Also adding @beckyjackson

**Comment by beckyjackson** [comment]
@mgiglio99 I've resolved the merge conflict, so we're all good on that :)

**Comment by mgiglio99** [comment]
Thanks Becky!
: )

**Pull request merged**
