### PR TITLE
Mam20200805

### PR DESCRIPTION
**Pull request by turbomam**
adding anatomical entities and cells in support of new specimens, #1197 

will add specimens themselves to biobank specimens template next and cite same issue

### CODE REVIEW

**Comment by turbomam** [comment]
wasn't offered a pull request button

**Comment by jamesaoverton** [comment]
Ok, this looks good. Can you please commit the updated `src/ontology/modules/biobank-specimens.owl`?

**Comment by turbomam** [comment]
I did the following, but it doesn't look like anything happened. I thought
I should check with you before doing anything else.

(base) ibi-admin-017:obi markampa$ git status

On branch mam20200805

Your branch is up to date with 'origin/mam20200805'.


nothing to commit, working tree clean

(base) ibi-admin-017:obi markampa$ git add
src/ontology/modules/biobank-specimens.owl

(base) ibi-admin-017:obi markampa$ git status

On branch mam20200805

Your branch is up to date with 'origin/mam20200805'.

Maybe there is a make command I still have to run? I don't think
src/ontology/modules/biobank-specimens.owl was updated, even on my computer.

(base) ibi-admin-017:obi markampa$ grep bodily
src/ontology/templates/biobank-specimens.tsv

OBI:2000009 bodily fluid specimen A specimen that is derived from some
bodily fluid Mark A. Miller|ORCID:0000-0001-9076-6066|Christian
Stoeckert|ORCID:0000-0002-5714-991X equivalent bodily fluid UBERON_0006314 Mark
A. Miller|ORCID:0000-0001-9076-6066|Christian
Stoeckert|ORCID:0000-0002-5714-991X

(base) ibi-admin-017:obi markampa$ grep bodily
src/ontology/modules/biobank-specimens.owl

thanks,
Mark

**Comment by jamesaoverton** [comment]
Ok. Can you run `make test`? That will build the template and update the module, then git will tell you that `src/ontology/modules/biobank-specimens.owl` has changed.

**Pull request merged**
