### PR TITLE
#1825 define and subclass Illumina sequencer serieses

### PR DESCRIPTION
**Pull request by turbomam**
closes
- #1825 

@jamesaoverton ~~some multi-quotes got messed up in this PR too. If you can show me how to fix one, then I can do the rest.~~

cc @aclum

### CODE REVIEW

**Comment by turbomam** [comment]
and

> ```shell
> java -jar build/robot.jar --prefix "REO: http://purl.obolibrary.org/obo/REO_" merge \
> --input src/ontology/obi-edit.owl \
> template \
> --template src/ontology/templates/devices.tsv \
> annotate \
> --ontology-iri "http://purl.obolibrary.org/obo/obi/dev/modules/devices.owl" \
> --output src/ontology/modules/devices.owl
> ```
> 
> ```
> MANCHESTER PARSE ERROR the expression ('has part' some container) at row 3, column 17 in table "src/ontology/templates/devices.tsv" cannot be parsed: encountered 'container', but expected one of:
> 	Class name
> 	( ... )
> 	{ ... }
> 	Self
> ```

**Comment by jamesaoverton** [comment]
All of the dark green quotation marks in the diff have been added by your editor, and are changing the semantics of the table. There's no point in debugging the ROBOT command until they're removed.

image

On the last PR, I used a text editor to manually remove them. People usually use Excel for editing these tables. I like https://www.visidata.org/. I haven't used LibreOffice in many years, so I don't know how it behaves.

**Comment by turbomam** [comment]
thanks. I get the sense that the ROBOT template error might be resolved when I fix the quotations marks

**Comment by turbomam** [comment]
Thanks @jamesaoverton @mgiglio99 @sebastianduesing 

I think I have implemented all of  the suggestions from today's meeting

**Comment by jamesaoverton** [comment]
OBI is strict about lowercase labels, so I changed "Series Instrument" to "series instrument". Is that ok with you @turbomam?

If so, I'll update the `devices.owl` and then merge this.

**Comment by turbomam** [comment]
> OBI is strict about lowercase labels, so I changed "Series Instrument" to "series instrument" throughout. Is that ok with you @turbomam?
> 
> If so, I'll update the `devices.owl` and then merge this.

Yes! Thank you.

**Comment by jamesaoverton** [comment]
Discussed on the OBI call 2024-10-21. We will release #1827, then merge this and make a new release candidate.

**Pull request merged**
