### PR TITLE
Add material processing template

### PR DESCRIPTION
**Pull request by beckyjackson**
From template WIP: https://docs.google.com/spreadsheets/d/1jDC-IbrBk_o1xxU8Z498ddI-P5HnGfB-Tms7PXDNWTw/edit#gid=0

### CODE REVIEW

**Comment by jamesaoverton** [comment]
When @hectorguzor is ready, let's add a check like #1463 to ensure that all the 'material processing' terms are only in the template, not left in `obi-edit.owl`

**Comment by jamesaoverton** [comment]
@hectorguzor I was waiting on some of your work, but I forget why. Are you planning to make changes to material processing in the near future?

**Comment by hectorguzor** [comment]
@jamesaoverton this PR still needs work. I haven't had a chance to work on it. I don't plan on making changes in the near future. I want to get back to this in a few months.

**Comment by jamesaoverton** [comment]
This is too far out of date, so I'll close it. If @hectorguzor has time, he'll make another attempt.

**Pull request closed without merging**
