### PR TITLE
enzyme activity assay #1303

### PR DESCRIPTION
**Pull request by turbomam**
just added the class, so that others can start adding subclasses

### CODE REVIEW

**Comment by jamesaoverton** [comment]
The definition currently ends with a question mark, so more work needs to be done here.

**Comment by johnwjudkins** [comment]
https://github.com/obi-ontology/obi/issues/1303

**Comment by beckyjackson** [comment]
Not sure what the status on this is, but I think the label needs to be lowercase. Is that correct?

**Comment by bpeters42** [comment]
These terms are useful. But current label and definition are problematic. There are also some discussions (Jennifer F with @jamesaoverton) on the logical modeling on how to capture 'enzymes' correctly.

**Comment by jamesaoverton** [comment]
Closed by #1572

**Pull request closed without merging**
